server:
  port: 8888



spring:
  datasource:
    url: jdbc:mysql://49.235.20.164:3306/confidant
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000 # 不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  resources:
    static-locations: classpath:/static/

  redis:
    host: 49.235.20.164

#logging:
#  level:
#    com:
#      zzr:
#        confidant:
#          mapper: debug

