server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://49.235.20.164:3306/confidant
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000 # 不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  #缓存设置
  cache:
    type: redis
  #redis配置
  redis:
    host: 49.235.20.164
    jedis:
      pool:
        # 最大空闲连接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 最大连接数（负数表示没有限制）
        max-active: -1
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
      # 链接超时时间（毫秒）
      timeout: 5000




  #配置css、js等静态资源访问路径
  resources:
    static-locations: classpath:/static/
  #配置thymeleaf
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
  #设置文件上传大小限制 30MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

#mapper 文件日志输出级别
logging:
  level:
    com.zzr.confidant.mapper: debug

mybatis-plus:
  #配置mapper.xml文件所在位置
  mapper-locations: classpath:mapper/*.xml
  #配置映射类所在位置
  type-aliases-package: com.zzr.confidant.mapper

#配置文件上传路径
file:
  upload:
    path: /Users/zzr/images/
    path.relative: /images/**



